openapi: 3.0.3
info:
  title: DRF Ecommerce API
  version: 1.0.0
  description: DRF Ecommerce API for django ninjas
paths:
  /api/brand//:
    get:
      operationId: api_brand_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/category//:
    get:
      operationId: api_category_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
  /api/product//:
    get:
      operationId: api_product_retrieve
      tags:
      - api
      security:
      - cookieAuth: []
      - basicAuth: []
      - {}
      responses:
        '200':
          description: No response body
components:
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
    cookieAuth:
      type: apiKey
      in: cookie
      name: sessionid
